---
title: "551 Project Proposal"
author: "Noah Kochanski and Mallory Wang"
date: "Due March 15, 2022"
output: html_document
---

## Project proposal: 
Introduce your project team members, propose a data set and plan what to do with it. Following the guidelines described below, you should write down a 2–3 pages plan for the project. Communicate to the instructors if you are unsure of the chosen data set and the methods you plan to pursue.

### Goal: 
The problem of interest is to estimate the expected carbon emission in G20 countries by 2050. Utilizing datasets for National Carbon Emission from CDIAC and UNFCCC by nation, we can make estimates for G20 countries across two different sources. The final goal is to develop a model for estimating carbon emissions for G20 countries and then generate predictions for next 25 years.  

### Data:
* How is the data collected?

From the Carbon Dioxide Information Analysis Center (CDIAC), 1959-2011 (and preliminary data for 2012-2014) estimates for fossil fuels are derived primarily from energy statistics published by the United Nations (2017), using the methods of Marland and Rotty (1984).

* Is the data a simple random sample from some population?

We can assume the data is simple random sample and it is definitely from some population.

* What is the potential defect in the data?

The data is country reported, calibrated by United Nations, which means data could not be accurate. However, for the purposes of this assignment, we will attempt to make estimates according to reported values as truths. Fortunately for us, the core data (carbon dioxide levels) requires very little cleaning as it is reviewed by the United Nations. We don't need to be concerned with missing data (for most countries; some countries started reporting information at a later date) or structural problems. We also don't need to worry about outliers; some countries might be considered outliers but we are picking United States and comparable country. 

We may include additional data outside of population and gdp. If we do, we will ensure follow general data cleaning methods. 

* If you were able to collect the data, what would you have done differently?

In a perfect scientific vacuum, we would have accurate sensors in all countries of interest that can measure the values for the entire country over the course of many years. 

* Are you going to account for the data collecting process in your analysis?

No. We will assume the data is correct. 

* Describe simple facts about the data: size, data structure source, etc.

55 data points (years) as vector. We do also have population and and GDP, also reported by countries, calibrated by United Nations. 

### Collaboration Plan:
* How are you going to divide the work? How often are you going to meet with each other?

We plan to collaborate equally on the work, meaning every aspect will be checked by the other member. We plan on meeting at least once a week but more fluidly, sync via text as needed. 

* For each group member: what is your role in the group project? What is your contribution so far? How do you plan to contribute further throughout the whole project?

We plan to do the work / roles equally for all parts of the project from code to write-up. 

### Project Plan
* What statistical model are you going to use for the data analysis?

We plan to start our analysis by understanding the distributions of our variables and how these distributions change over time. Using this analysis, we will fit appropriate prior distributions to all of our variables and perform Bayesian linear regression. We then will then leave out most recent years from the dataset and see how well our model performs at prediction in the short term. Depending on how well our model does, we will then fit our model to the entire dataset and extrapolate predictions outside of the dataset.

* Have you done any preliminary analysis of the data?

Very early analysis of our data shows that G20 countries lack issues of scarcity over all variables of interest.

* What is your group’s time line for (1) propose and fit a preliminary model, (2) examine initial results and adjust models further if needed, (3) prepare for a presentation, (4) summarize and write a final report.

Our project timeline is as follows: 

(1) EDA and preliminary model completed by 3/25
(2) Initial results and adjustments completed by 4/8
(3) Preparations for presentation completed by 4/15
(4) Final report completed by 4/15

Final report can be done in tandem with other aspects of the project.

* What are the (potential) difficulties with your data analysis?

Since this is real data, there could be the possibility that our data does not (or we do not know what) fit distribution well, ie. for prior. If we produce posteriors that heavily relies on prior, we could generate biased results. We could also run into computation issues when seeking conversion on simulated steps. 

```{r}

```
